# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master

resources:
- repo: self
  clean: true

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build Images + Push to ACR
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: "Build Images"
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'acrsitecoredev'
        dockerComposeFile: '**/docker-compose.yml'
        additionalDockerComposeFiles: 'docker-compose.override.yml'
        dockerComposeFileArgs: '$(DOCKER_COMPOSE_ARGS)'
        qualifyImageNames: false
        action: 'Build services'
        additionalImageTags: '$(Build.BuildNumber)-$(Build.SourceBranchName)'
        includeLatestTag: true
    - task: DockerCompose@0
      displayName: "Push Images with Latest Tag"
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'be84010d-9f63-4ec5-9f9f-2b51f25643fa'
        azureContainerRegistry: 'acrsitecoredev'
        dockerComposeFile: '**/docker-compose.yml'
        additionalDockerComposeFiles: 'docker-compose.override.yml'
        dockerComposeFileArgs: '$(DOCKER_COMPOSE_ARGS)'
        action: 'Push services'
        additionalImageTags: '$(Build.BuildNumber)-$(Build.SourceBranchName)'
        includeLatestTag: true
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))